[build.environment]
    REACT_APP_CLIENT_ID=289466662721-f1sj8vu0c15fioleb134nr0oo0ppfk8t.apps.googleusercontent.com
    REACT_APP_CLOUDINARY_API_KEY=396889155975552
    REACT_APP_CLOUDINARY_API_SECRET=ajbLleqQ-d1TqTwx9qTTSz-6m5A
    REACT_APP_CLOUDINARY_API_CLOUDINARY_URL=cloudinary://396889155975552:ajbLleqQ-d1TqTwx9qTTSz-6m5A@shanklandium
    REACT_APP_UPLOAD_IMAGE=https://api.cloudinary.com/v1_1/shanklandium/image/upload
    REACT_APP_UPLOAD_PRESET=crmFiles